global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: '/metrics'

  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:4001']
    metrics_path: '/metrics'

  - job_name: 'sync-service'
    static_configs:
      - targets: ['host.docker.internal:4002']
    metrics_path: '/metrics'